CREATE TABLE event (event_id VARCHAR(255) PRIMARY KEY NOT NULL,
description VARCHAR(255) NOT NULL,
destination VARCHAR(50) NOT NULL,
duration VARCHAR(50) NOT NULL,
price DECIMAL(10,2) NOT NULL,
tour_type VARCHAR(255) NOT NULL)


SELECT * FROM event